FROM php:8.4-fpm

RUN docker-php-ext-install mysqli pdo pdo_mysql

# Install required dependencies
RUN apt-get update -y && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libjpeg-dev \
    libwebp-dev \
    libxpm-dev \
    sendmail \
    curl \
    unzip \
    git \
    && docker-php-ext-configure gd --with-jpeg \
    && docker-php-ext-install gd

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Verify Composer installation
RUN composer --version

# XDebug
RUN pecl channel-update pecl.php.net && \
     pecl install xdebug-3.4.1 && \
     docker-php-ext-enable xdebug
